config/routes.rb
Rails.application.routes.draw do
  root to: 'cities#index' # root route of the application
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  devise_scope :user do  
    get '/users/sign_out', to: 'devise/sessions#destroy'  
  end
  
  resources :employees # to route all crud operation
  resources :cities  # to route all crud operation 
  
  get "managers", to: "employees#show_manager" #create route to show managers 
  get "count", to: "employees#cityemp" # to count the the no. of employee in particular city
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    before_validation :normalize_name  #callback use to save titlesize name before saving

    validates :name, presence: true ,uniqueness: { case_sensitive: true } # validation use to check presence and uniqueness 
    belongs_to :employee, :optional => true # one to one city belong to an employee 
    
    private
        def normalize_name
            self.name = name.titleize
        end
    
end

app/models/employee.rb
class Employee < ApplicationRecord
    mount_uploader :avatar, AvatarUploader # to link  uploder 
    validates :name, :city_id ,presence: true # validation use to check the presenence 
    has_one :city # one to one relation with city model 
    # self join in employee table
    has_many :subordinates, class_name: "Employee", foreign_key: "manager_id" 
    belongs_to :manager, class_name: "Employee", optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  def self.from_omniauth(auth)  
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
          end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
    def facebook
        @user= User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  #befor_action set_city to find the city in db befor do show edit update and destroy
  before_action :set_city, only: [:show,:edit,:update,:destroy] 
  # if user is not autenticated only show index and show method is use 
  before_action :authenticate_user!,except: [:index ,:show]
  
  #will paginate use to show now of row in per page 
  WillPaginate.per_page = 5
  def index
    @cities =City.page(params[:page]) #use of pagination in city 
    
  end
 
 
  def new
    @city = City.new
  end

  def create
    @city =City.new(city_params)
    respond_to do |format|
      if @city.save
        format.html { redirect_to @city ,notice: 'city created'}
      else 
        format.html { render :edit }
       
      end
    end
  end

  def show
  end

  def edit
  end
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city ,notice: 'city update'}
     
      else 
        format.html { render :edit }
      end
    end
  end
  def destroy 
    respond_to do |format|
      if @city.destroy
        format.html { redirect_to @city,notice: 'city destroy' }
    
    else 
      format.html { redirect_to @city ,notice: 'Error'}
    end
    end
  end
    
  

  private
    def city_params
      params.require(:city).permit(:name)
    end
    def set_city
      @city = City.find(params[:id])
    end
  

  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  #befor_action set_city to find the city in db befor do show edit update and destroy
  before_action :set_employee, only: [:show, :edit, :update, :destroy]


  # if user is not autenticated only show index and show method is use 
  before_action :authenticate_user!,except: [:index ,:show,:show_manager]


  #will paginate use to show now of row in per page 
  WillPaginate.per_page = 5



  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.page(params[:page]) #pagination on index of employee
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
   
    
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # route "/managers" to show all the managers
  def show_manager
    # to find all the employee which have manager
    @managers=Employee.where.not(manager_id:nil) 
    #to find all manager_id and paginate "and we change in config array/paginate "
    @managers=@managers.uniq {|obj| obj.manager_id }.paginate(page:params[:page],per_page:5) 
  end


  # route "/count" to count the employee in city
  def cityemp
    id=params[:city_id]
    @count=Employee.where(city_id:id).count #query to count employee in city
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      # add new param to pass image using carrier wave and remove_avatar is to pass checkbox value
      params.require(:employee).permit(:name, :city_id, :manager_id,:avatar,:remove_avatar) 
    end

    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
    # to check wheather the current user is admin or not
    def new_city
        if user_signed_in? && current_user.admin
            "<a href='#{new_city_path}' >New city</a>".html_safe
        end
    end
    
    def edit_city(city)
        if user_signed_in? && current_user.admin
            "<a href='#{edit_city_path(city)}' >Edit</a>".html_safe
        end
    end

   
end

app/helpers/employees_helper.rb
module EmployeesHelper
    # to check wheather the current user is admin or not
    def new_emp
        if user_signed_in? && current_user.admin
            "<a href='#{new_employee_path}'>Add employee</a>".html_safe
        end
    end
    def edit_emp(employee)
        if user_signed_in? && current_user.admin
            "<a href='#{edit_employee_path(employee)}'>Edit</a>".html_safe
        end
    end
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name,class:"form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

 
<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope='col'>Name</th>
      
      <th scope="col">Show</th>
      <% if user_signed_in? && current_user.admin %>
      <th scope="col">Edit</th>
      <th scope="col">Destroy</th>
      <% end %>
      
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td style="text-transform: capitalize;"><%= city.name %></td>
        
        <td><%= link_to 'Show', city  %></td>
        <td><%= edit_city(city) %></td>
        <% if user_signed_in? && current_user.admin %>
        <td><%= button_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-primary"%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= new_city %>

<br><br>
<%= will_paginate @city ,renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>

app/views/cities/new.html.erb
<h1>New City</h1>


<%= render 'form', city: @city %>


<%= link_to 'Back', cities_path ,class:"btn btn-secondary"%>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>
<%= edit_city(@city) %>

<%= link_to 'Back', cities_path %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name ,class:"form-control"%>
  </div>
  <br>
  <br>
   <div class="form-row">
      <div class="form-group col-md-4">
      <%= form.label :city_id %>
      <%= form.collection_select :city_id, City.order(:name),:id,:name, include_blank: true %>
      <span id="result"></span>
      </div>

      <div class="form-group col-md-4">
          <%= form.label :manager_id %>
          <%= form.collection_select :manager_id, Employee.order(:name),:id,:name,include_blank: true,class:"form-control" %>
      </div>
    </div>
  <div class="field">
  <%= form.label :avatar %>
    <%= form.file_field :avatar  %>
  <% if @employee.avatar? %>
    <%= image_tag(@employee.avatar_url)  %>
    <br>
    <%= form.check_box :remove_avatar %>Remove avatar
  <% end %>
    
  </div>

  <div class="actions">
    <%= form.submit id:"submit" %>
  </div>
<% end %>

app/views/employees/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Myapp',root_path,class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to 'Managers ',managers_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'Emplyoees',employees_path, class:"nav-link" %>
      </li>
      <!-- To check wheather a user is login or not -->
      <% if user_signed_in? %>
       <li class="nav-item">
       <!-- To show the name of user -->
      <%= link_to current_user.email.split('@')[0].capitalize, edit_user_registration_path, method: :delete, class:"nav-link" %>
      </li>

       <li class="nav-item">
      <%= link_to :logout, destroy_user_session_path, method: :delete, class:"nav-link"  %>
      </li>
     
      
      <% else %>
      
      <li class="nav-item">
      <%= link_to 'Sign up',new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign in',new_user_session_path, class:"nav-link" %>
      </li>
     
      <% end %>
     
 
     
    </ul>

     
   
   
  </div>
</nav>

app/views/employees/cityemp.js.erb
// TO disable the button and show the message for add employee form
var count = <%= @count %>
console.log(count);
if(count < 4){
$("#submit").attr("disabled", false);

$("#result").html("Hello welcome to this city "+count);


}
else{
 $("#submit").attr("disabled", true);

$("#result").html("No we are full in this city "+count);

}

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
       
          <td><%= City.find(employee.city_id).name %></td>
        <% if employee.manager_id  %>
          <td><%= Employee.find(employee.manager_id).name %></td>
        <% else %>
           <td></td>
        <% end %>
      
        <td><%= link_to 'Show', employee %></td>
        
        <!-- use of helper to check the user is admin or not  -->
        <td><%=  edit_emp(employee) %></td>
        <% if user_signed_in? && current_user.admin %>
        <td><%= button_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- use of helper to check the user is admin or not  -->
<%= new_emp %>






<br>
<br><br>
<%= will_paginate @city ,renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>

app/views/employees/new.html.erb
<h1>New Employee</h1>


<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<% if @employee.avatar?   %>

<img src="<%= @employee.avatar  %>" class="float-right" style="width:200px;height:200px;">
<% else %>
<img src="/uploads/employee/avatar/21/download__1_.png" class="float-right">
<% end %>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

 <p>
  <strong>City:</strong><%= City.find(@employee.city_id).name %>
  
</p>

<p>
  <strong>Manager:</strong>
   <% if @employee.manager_id  %>
  <%=   Employee.find(@employee.manager_id ).name %>
  <% end %>
</p>

<!-- use of helper to check the user is admin or not  -->
<%= edit_emp(@employee) %> 

<%= link_to 'Back', employees_path %>

app/views/employees/show_manager.html.erb
<h1>Managers</h1>
<table class="table table-bordered table-hover">
  <thead class="thead-dark"> 
    <tr>
      <th>Manager</th>
      <th>City</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= Employee.find(manager.manager_id).name %></td>
        <td><%= City.find(Employee.find(manager.manager_id).city_id).name %></td>
       
        
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @managers ,renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>Assigment</title>
     
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag "preyield" %>
    
  </head>
  <body>

    <!-- To render the header partial -->
    <%= render 'employees/header' %>


    <!-- To render alert patial -->
    <%= render 'employees/alert' %> 

    
    <div class="container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%= javascript_include_tag "postyield" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>